### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [ohes/nanana#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by ohes** [comment]
Used the viewport tag and I think it looks much better on my phone now!

**Comment by MarcoMorawec** [comment]
Nice @ohes.

Can you include the link to the specific commit where you added the viewport tag in a comment below - right now I can't see any viewport tag addition in your code (maybe you forgot to push up your latest commits to GitHub)

**Comment by ohes** [comment]
Hi Marco, does this look correct?

https://github.com/ohes/nanana/blob/master/app/views/layouts/application.html.erb

**Comment by MarcoMorawec** [comment]
@ohes :+1: 

Make sure you close the issue, not that you solved it :)
